
import { ILocation } from '@/common/CommonLocationCardModal';
import img from '../assets/featured.jpg';
import rating from '../assets/Home/rating.png';


export const locationData: ILocation[] = [
  {
    id: "1",
    image: img,
    title: "Piccadilly Circus, London",
    category: "new",
    screenSize: "15m x 10m (approx. 49ft x 33ft)",
    description: "Dominate a key European intersection with iconic digital billboards.",
    lat: 51.5074,
    lng: -0.128,
    availability: "available",
    reach: 2000000,
    price: 5000,
    campaigns: 3,
    status: "active",
    location: "London, UK",
    tierLevel: "Premium",
    costPerPlay: 100,
  },
  {
    id: "2",
    image: img,
    title: "Times Square, NYC",
    category: "new",
    screenSize: "15m x 10m (approx. 49ft x 33ft)",
    description: "Reach millions in the heart of global commerce and entertainment.",
    lat: 40.7580,
    lng: -73.9855,
    availability: "available",
    reach: 5000000,
    price: 7000,
    campaigns: 5,
    status: "active",
    location: "New York City, USA",
    tierLevel: "Standard",
    costPerPlay: 120,
  },
  {
    id: "3",
    image: img,
    title: "Shibuya Crossing, Tokyo",
    category: "new",
    screenSize: "15m x 10m (approx. 49ft x 33ft)",
    description: "Capture the attention of millions at the world's busiest pedestrian crossing.",
    lat: 35.6595,
    lng: 139.7004,
    availability: "available",
    reach: 3000000,
    price: 6000,
    campaigns: 4,
    status: "active",
    location: "Tokyo, Japan",
    tierLevel: "Premium",
    costPerPlay: 110,
  },
  {
    id: "4",
    image: img,
    title: "Champs-Élysées, Paris",
    category: "new",
    screenSize: "15m x 10m (approx. 49ft x 33ft)",
    description: "Showcase your brand on the most famous avenue in Paris.",
    lat: 48.8566,
    lng: 2.3522,
    availability: "maintenance",
    reach: 1500000,
    price: 4500,
    campaigns: 2,
    status: "maintenance",
    location: "Paris, France",
    tierLevel: "Basic",
    costPerPlay: 90,
  },
  {
    id: "5",
    image: img,
    title: "Gangnam District, Seoul",
    category: "new",
    screenSize: "15m x 10m (approx. 49ft x 33ft)",
    description: "Display your message in South Korea's trendiest neighborhood.",
    lat: 37.4979,
    lng: 127.0276,
    availability: "available",
    reach: 1000000,
    price: 5500,
    campaigns: 3,
    status: "active",
    location: "Seoul, South Korea",
    tierLevel: "Standard",
    costPerPlay: 100,
  },
  {
    id: "6",
    image: img,
    title: "Sydney Harbour, Sydney",
    category: "new",
    screenSize: "15m x 10m (approx. 49ft x 33ft)",
    description: "Iconic views and massive audience in Sydney's core.",
    lat: -33.8688,
    lng: 151.2093,
    availability: "available",
    reach: 4000000,
    price: 8000,
    campaigns: 6,
    status: "active",
    location: "Sydney, Australia",
    tierLevel: "Premium",
    costPerPlay: 150,
  },
  {
    id: "7",
    image: img,
    title: "Dubai Mall, Dubai",
    category: "new",
    screenSize: "18m x 12m (approx. 59ft x 39ft)",
    description: "Reach affluent shoppers at the world's largest shopping mall.",
    lat: 25.1972,
    lng: 55.2744,
    availability: "available",
    reach: 2500000,
    price: 7500,
    campaigns: 4,
    status: "active",
    location: "Dubai, UAE",
    tierLevel: "Premium",
    costPerPlay: 180,
  },
  {
    id: "8",
    image: img,
    title: "Rodeo Drive, Los Angeles",
    category: "new",
    screenSize: "12m x 8m (approx. 39ft x 26ft)",
    description: "Target luxury consumers in Beverly Hills' famous shopping district.",
    lat: 34.0736,
    lng: -118.4004,
    availability: "available",
    reach: 1200000,
    price: 6500,
    campaigns: 3,
    status: "active",
    location: "Los Angeles, USA",
    tierLevel: "Standard",
    costPerPlay: 130,
  },
  {
    id: "9",
    image: img,
    title: "Ginza District, Tokyo",
    category: "new",
    screenSize: "14m x 9m (approx. 46ft x 30ft)",
    description: "Premium advertising in Tokyo's luxury shopping and entertainment district.",
    lat: 35.6719,
    lng: 139.7639,
    availability: "booked",
    reach: 1800000,
    price: 5800,
    campaigns: 2,
    status: "inactive",
    location: "Tokyo, Japan",
    tierLevel: "Standard",
    costPerPlay: 105,
  },
  {
    id: "10",
    image: img,
    title: "Las Vegas Strip",
    category: "top",
    screenSize: "20m x 15m (approx. 66ft x 49ft)",
    description: "Stand out in the entertainment capital of the world.",
    lat: 36.1699,
    lng: -115.1398,
    availability: "available",
    reach: 7000000,
    price: 10000,
    campaigns: 8,
    status: "active",
    location: "Las Vegas, USA",
    tierLevel: "Premium",
    costPerPlay: 200,
  },
  {
    id: "11",
    image: img,
    title: "Shinjuku Station, Tokyo",
    category: "top",
    screenSize: "16m x 11m (approx. 52ft x 36ft)",
    description: "Reach commuters at the world's busiest transportation hub.",
    lat: 35.6895,
    lng: 139.7004,
    availability: "available",
    reach: 3500000,
    price: 8500,
    campaigns: 7,
    status: "active",
    location: "Tokyo, Japan",
    tierLevel: "Premium",
    costPerPlay: 170,
  },
  {
    id: "12",
    image: img,
    title: "Orchard Road, Singapore",
    category: "top",
    screenSize: "15m x 10m (approx. 49ft x 33ft)",
    description: "Prime advertising in Singapore's famous shopping belt.",
    lat: 1.3048,
    lng: 103.8318,
    availability: "available",
    reach: 2200000,
    price: 7200,
    campaigns: 5,
    status: "active",
    location: "Singapore",
    tierLevel: "Premium",
    costPerPlay: 160,
  },
  {
    id: "13",
    image: img,
    title: "Hong Kong Central",
    category: "top",
    screenSize: "17m x 12m (approx. 56ft x 39ft)",
    description: "Dominate the financial heart of Asia with premium digital displays.",
    lat: 22.2795,
    lng: 114.1628,
    availability: "available",
    reach: 2800000,
    price: 8800,
    campaigns: 6,
    status: "active",
    location: "Hong Kong",
    tierLevel: "Premium",
    costPerPlay: 190,
  },
  {
    id: "14",
    image: img,
    title: "Miami South Beach",
    category: "top",
    screenSize: "14m x 9m (approx. 46ft x 30ft)",
    description: "Capture the vibrant tourist and local audience in Miami's iconic beachfront.",
    lat: 25.7877,
    lng: -80.1311,
    availability: "available",
    reach: 1800000,
    price: 6800,
    campaigns: 4,
    status: "active",
    location: "Miami, USA",
    tierLevel: "Standard",
    costPerPlay: 140,
  },
  {
    id: "15",
    image: img,
    title: "Milan Fashion District",
    category: "top",
    screenSize: "13m x 8m (approx. 43ft x 26ft)",
    description: "Target fashion-conscious audiences in the world's fashion capital.",
    lat: 45.4686,
    lng: 9.1815,
    availability: "available",
    reach: 1600000,
    price: 6200,
    campaigns: 3,
    status: "active",
    location: "Milan, Italy",
    tierLevel: "Standard",
    costPerPlay: 125,
  },
  {
    id: "16",
    image: img,
    title: "Toronto Yonge-Dundas Square",
    category: "top",
    screenSize: "15m x 10m (approx. 49ft x 33ft)",
    description: "Canada's busiest intersection and premier advertising location.",
    lat: 43.6565,
    lng: -79.3805,
    availability: "available",
    reach: 1900000,
    price: 5900,
    campaigns: 4,
    status: "active",
    location: "Toronto, Canada",
    tierLevel: "Standard",
    costPerPlay: 115,
  },
  {
    id: "17",
    image: img,
    title: "Berlin Alexanderplatz",
    category: "top",
    screenSize: "16m x 11m (approx. 52ft x 36ft)",
    description: "Central Berlin location with high foot traffic and visibility.",
    lat: 52.5219,
    lng: 13.4132,
    availability: "available",
    reach: 2100000,
    price: 6300,
    campaigns: 4,
    status: "active",
    location: "Berlin, Germany",
    tierLevel: "Standard",
    costPerPlay: 135,
  },
  {
    id: "18",
    image: img,
    title: "São Paulo Paulista Avenue",
    category: "top",
    screenSize: "18m x 12m (approx. 59ft x 39ft)",
    description: "Prime advertising on South America's most important financial corridor.",
    lat: -23.5614,
    lng: -46.6550,
    availability: "available",
    reach: 3200000,
    price: 7700,
    campaigns: 5,
    status: "active",
    location: "São Paulo, Brazil",
    tierLevel: "Premium",
    costPerPlay: 155,
  },
  {
    id: "19",
    image: img,
    title: "London Eye, London",
    category: "fav",
    screenSize: "15m x 10m (approx. 49ft x 33ft)",
    description: "Iconic riverside location with millions of annual visitors.",
    lat: 51.5033,
    lng: -0.1195,
    availability: "available",
    reach: 2300000,
    price: 6700,
    campaigns: 5,
    status: "active",
    location: "London, UK",
    tierLevel: "Premium",
    costPerPlay: 145,
  },
  {
    id: "20",
    image: img,
    title: "Central Park, NYC",
    category: "fav",
    screenSize: "14m x 9m (approx. 46ft x 30ft)",
    description: "Capture the attention of millions visiting NYC's most famous park.",
    lat: 40.7812,
    lng: -73.9665,
    availability: "available",
    reach: 2600000,
    price: 7100,
    campaigns: 4,
    status: "active",
    location: "New York City, USA",
    tierLevel: "Standard",
    costPerPlay: 150,
  },
  {
    id: "21",
    image: img,
    title: "Eiffel Tower, Paris",
    category: "fav",
    screenSize: "16m x 11m (approx. 52ft x 36ft)",
    description: "Advertising at the world's most visited paid monument.",
    lat: 48.8584,
    lng: 2.2945,
    availability: "booked",
    reach: 2900000,
    price: 8900,
    campaigns: 6,
    status: "inactive",
    location: "Paris, France",
    tierLevel: "Premium",
    costPerPlay: 210,
  },
  {
    id: "22",
    image: img,
    title: "Venice Beach, Los Angeles",
    category: "fav",
    screenSize: "13m x 8m (approx. 43ft x 26ft)",
    description: "Reach the eclectic crowd at LA's most famous beachfront.",
    lat: 33.9850,
    lng: -118.4695,
    availability: "available",
    reach: 1400000,
    price: 5800,
    campaigns: 3,
    status: "active",
    location: "Los Angeles, USA",
    tierLevel: "Standard",
    costPerPlay: 120,
  },
  {
    id: "23",
    image: img,
    title: "Amsterdam Dam Square",
    category: "fav",
    screenSize: "14m x 9m (approx. 46ft x 30ft)",
    description: "Historic city center location with high tourist traffic.",
    lat: 52.3731,
    lng: 4.8924,
    availability: "available",
    reach: 1700000,
    price: 6100,
    campaigns: 3,
    status: "active",
    location: "Amsterdam, Netherlands",
    tierLevel: "Standard",
    costPerPlay: 125,
  },
  {
    id: "24",
    image: img,
    title: "Sydney Opera House",
    category: "fav",
    screenSize: "15m x 10m (approx. 49ft x 33ft)",
    description: "Advertising at Australia's most iconic cultural landmark.",
    lat: -33.8568,
    lng: 151.2153,
    availability: "available",
    reach: 2400000,
    price: 7800,
    campaigns: 5,
    status: "active",
    location: "Sydney, Australia",
    tierLevel: "Premium",
    costPerPlay: 175,
  },
  {
    id: "25",
    image: img,
    title: "Rio Copacabana Beach",
    category: "fav",
    screenSize: "17m x 12m (approx. 56ft x 39ft)",
    description: "Reach millions of beachgoers at one of the world's most famous beaches.",
    lat: -22.9712,
    lng: -43.1826,
    availability: "available",
    reach: 2700000,
    price: 7400,
    campaigns: 4,
    status: "active",
    location: "Rio de Janeiro, Brazil",
    tierLevel: "Premium",
    costPerPlay: 165,
  },
  {
    id: "26",
    image: img,
    title: "Prague Old Town Square",
    category: "fav",
    screenSize: "13m x 8m (approx. 43ft x 26ft)",
    description: "Historic central European location with high tourist appeal.",
    lat: 50.0875,
    lng: 14.4213,
    availability: "available",
    reach: 1500000,
    price: 5400,
    campaigns: 2,
    status: "active",
    location: "Prague, Czech Republic",
    tierLevel: "Basic",
    costPerPlay: 95,
  },
  {
    id: "27",
    image: img,
    title: "Istanbul Taksim Square",
    category: "fav",
    screenSize: "16m x 11m (approx. 52ft x 36ft)",
    description: "Prime advertising in the heart of Istanbul's commercial and entertainment district.",
    lat: 41.0351,
    lng: 28.9833,
    availability: "available",
    reach: 2300000,
    price: 6900,
    campaigns: 4,
    status: "active",
    location: "Istanbul, Turkey",
    tierLevel: "Standard",
    costPerPlay: 140,
  }
];


export const StepsData = [
  {
    "id": "1",
    "stepNumber": "Step 1:",
    "title": "Select Your Boards",
    "description": "Browse our extensive network of digital billboards. Choose locations based on geography, audience demographics, and real-time availability",
    "icon": "location"
  },
  {
    "id": "2",
    "stepNumber": "Step 2:",
    "title": "Schedule Ad's Times",
    "description": "Define your campaign's duration, frequency, and specific display times. Optimize for peak hours or continuous brand presence effortlessly.",
    "icon": "calendar"
  },
  {
    "id": "3",
    "stepNumber": "Step 3:",
    "title": "Upload Your Creative",
    "description": "Easily upload your high-resolution images or videos. Our platform ensures seamless integration and optimal display across all selected screens.",
    "icon": "upload"
  }
]
export const PricingData = [
  {
    "id": "1",
    "title": "Screen Tier",
    "description": "Billboards are categorized into tiers (Tier 1: Prime, Tier 2: Mid, Tier 3: Low) reflecting their premium visibility and audience reach. Prime locations naturally command a higher base CPP.",
    "icon": "layers"
  },
  {
    "id": "2",
    "title": "Time of Day",
    "description": "Advertising during prime hours (e.g., morning commutes, lunch breaks, evening rush) costs more due to increased audience exposure. Our system optimizes for your chosen schedule.",
    "icon": "clock"
  },
  {
    "id": "3",
    "title": "Traffic Value",
    "description": "Screens located in areas with consistently high foot or vehicular traffic yield a higher base CPP, reflecting the greater potential for impressions and engagement.",
    "icon": "trending-up"
  },
  {
    "id": "4",
    "title": "Bid Competition",
    "description": "In high-demand scenarios where multiple advertisers are vying for the same slot, increased competition may lead to a higher effective CPP to secure your desired placement.",
    "icon": "lightbulb"
  }
]
export const RatingData = [
  {
    "id": "1",
    "name": "Wade Warren",
    "location": "London, UK",
    "comment": "The booking process was easy, and the villa was fantastic. I highly recommend it!",
    "rating": 5.0,
    "profileImage": rating,
  },
  {
    "id": "2",
    "name": "Esther Howard",
    "location": "New York, USA",
    "comment": "Amazing experience! The villa exceeded expectations. Booking was simple!",
    "rating": 4.5,
    "profileImage": rating,
  },
  {
    "id": "3",
    "name": "Robert Fox",
    "location": "Paris, France",
    "comment": "Had an incredible stay! The villa was perfect, and booking was smooth.",
    "rating": 4.8,
    "profileImage": rating,
  },
  {
    "id": "4",
    "name": "Sophie Turner",
    "location": "Los Angeles, USA",
    "comment": "The villa was great, and the booking experience was seamless. Definitely recommend!",
    "rating": 2,
    "profileImage": rating,
  },
  {
    "id": "5",
    "name": "David Smith",
    "location": "Sydney, Australia",
    "comment": "Absolutely loved the villa! Everything was perfect and easy to book.",
    "rating": 1,
    "profileImage": rating,
  },
  {
    "id": "6",
    "name": "Emily Johnson",
    "location": "Toronto, Canada",
    "comment": "The villa was even better than expected. The booking process was quick and easy!",
    "rating": 1.5,
    "profileImage": rating,
  },
  {
    "id": "7",
    "name": "Michael Brown",
    "location": "Berlin, Germany",
    "comment": "Perfect stay, very convenient booking system. The villa was stunning!",
    "rating": 3.6,
    "profileImage": rating,
  },
  {
    "id": "8",
    "name": "Alice Williams",
    "location": "Madrid, Spain",
    "comment": "It was an amazing experience. Easy booking and the villa was wonderful.",
    "rating": 4.5,
    "profileImage": rating,
  },
  {
    "id": "9",
    "name": "Tom Clark",
    "location": "Rome, Italy",
    "comment": "Fantastic villa and very easy to book. Highly recommend!",
    "rating": 4.8,
    "profileImage": rating,
  },
];


export const FaqData = [
  {
    "id": "1",
    "question": "How do I get started with SCNE Ads?",
    "answer": "To get started, simply sign up on our website, create an account, and then you can begin uploading your ad materials (images or videos). After that, you can select the locations, schedule your ads, set your budget, and launch your campaign!"
  },
  {
    "id": "2",
    "question": "How do I choose the location for my ads?",
    "answer": "You can browse our extensive network of digital billboards through our interactive map. Filter locations by geography, audience demographics, traffic patterns, and real-time availability. Our platform provides detailed analytics for each location to help you make informed decisions."
  },
  {
    "id": "3",
    "question": "What is the appointment booking feature?",
    "answer": "The appointment booking feature allows you to schedule consultations with our advertising specialists. They can help you optimize your campaign strategy, select the best locations, and provide personalized recommendations based on your target audience and budget."
  },
  {
    "id": "4",
    "question": "How is the pricing for my campaign determined?",
    "answer": "Our dynamic pricing engine considers multiple factors: screen tier (Prime, Mid, Low), time of day (peak vs off-peak hours), traffic value of the location, and bid competition. This ensures fair pricing while maximizing your campaign's effectiveness and ROI."
  },
  {
    "id": "5",
    "question": "What types of ads can I upload?",
    "answer": "You can upload high-resolution images (JPEG, PNG) and videos (MP4, MOV) up to 30 seconds long. We support various aspect ratios and our platform automatically optimizes your content for different screen sizes. All content must comply with our advertising guidelines."
  }
]
export const CountryCodes = [
  { label: "Australia", code: "AU", value: "+61" },
  { label: "United States", code: "US", value: "+1" },
  { label: "United Kingdom", code: "GB", value: "+44" },
  { label: "India", code: "IN", value: "+91" },
  { label: "Canada", code: "CA", value: "+1" },
  { label: "Germany", code: "DE", value: "+49" },
  { label: "France", code: "FR", value: "+33" },
  { label: "Italy", code: "IT", value: "+39" },
  { label: "Brazil", code: "BR", value: "+55" },
  { label: "Mexico", code: "MX", value: "+52" },
  { label: "Spain", code: "ES", value: "+34" },
  { label: "Japan", code: "JP", value: "+81" },
  { label: "South Korea", code: "KR", value: "+82" },
  { label: "Russia", code: "RU", value: "+7" },
  { label: "China", code: "CN", value: "+86" },
  { label: "Saudi Arabia", code: "SA", value: "+966" },
  { label: "South Africa", code: "ZA", value: "+27" },
  { label: "Nigeria", code: "NG", value: "+234" },
  { label: "Egypt", code: "EG", value: "+20" },
  { label: "Pakistan", code: "PK", value: "+92" },
  { label: "Bangladesh", code: "BD", value: "+880" },
  { label: "Argentina", code: "AR", value: "+54" },
  { label: "Turkey", code: "TR", value: "+90" },
  { label: "Ukraine", code: "UA", value: "+380" },
  { label: "Poland", code: "PL", value: "+48" },
  { label: "Thailand", code: "TH", value: "+66" },
  { label: "Vietnam", code: "VN", value: "+84" },
  { label: "Chile", code: "CL", value: "+56" },
  { label: "Colombia", code: "CO", value: "+57" },
  { label: "Peru", code: "PE", value: "+51" },
  { label: "Indonesia", code: "ID", value: "+62" },
  { label: "Malaysia", code: "MY", value: "+60" },
  { label: "Singapore", code: "SG", value: "+65" },
  { label: "Israel", code: "IL", value: "+972" },
  { label: "Greece", code: "GR", value: "+30" },
  { label: "Portugal", code: "PT", value: "+351" },
  { label: "New Zealand", code: "NZ", value: "+64" },
  { label: "Ireland", code: "IE", value: "+353" },
  { label: "Sweden", code: "SE", value: "+46" },
  { label: "Norway", code: "NO", value: "+47" },
  { label: "Denmark", code: "DK", value: "+45" },
  { label: "Finland", code: "FI", value: "+358" },
  { label: "Netherlands", code: "NL", value: "+31" },
  { label: "Belgium", code: "BE", value: "+32" },
  { label: "Austria", code: "AT", value: "+43" },
  { label: "Switzerland", code: "CH", value: "+41" },
  { label: "Poland", code: "PL", value: "+48" },
  { label: "Romania", code: "RO", value: "+40" },
  { label: "Bulgaria", code: "BG", value: "+359" },
  { label: "Serbia", code: "RS", value: "+381" },
  { label: "Croatia", code: "HR", value: "+385" },
  { label: "Slovakia", code: "SK", value: "+421" },
  { label: "Hungary", code: "HU", value: "+36" },
  { label: "Czech Republic", code: "CZ", value: "+420" },
  { label: "Slovenia", code: "SI", value: "+386" },
  { label: "Lithuania", code: "LT", value: "+370" },
  { label: "Latvia", code: "LV", value: "+371" },
  { label: "Estonia", code: "EE", value: "+372" },
  { label: "Malta", code: "MT", value: "+356" },
  { label: "Cyprus", code: "CY", value: "+357" },
  { label: "Iceland", code: "IS", value: "+354" },
  { label: "Luxembourg", code: "LU", value: "+352" },
  { label: "Monaco", code: "MC", value: "+377" },
  { label: "Andorra", code: "AD", value: "+376" },
  { label: "Liechtenstein", code: "LI", value: "+423" },
  { label: "San Marino", code: "SM", value: "+378" },
  { label: "Vatican City", code: "VA", value: "+379" },
  { label: "Armenia", code: "AM", value: "+374" },
  { label: "Georgia", code: "GE", value: "+995" },
  { label: "Azerbaijan", code: "AZ", value: "+994" },
  { label: "Kazakhstan", code: "KZ", value: "+7" },
  { label: "Kyrgyzstan", code: "KG", value: "+996" },
  { label: "Uzbekistan", code: "UZ", value: "+998" },
  { label: "Tajikistan", code: "TJ", value: "+992" },
  { label: "Turkmenistan", code: "TM", value: "+993" },
  { label: "Mongolia", code: "MN", value: "+976" },
  { label: "Nepal", code: "NP", value: "+977" },
  { label: "Sri Lanka", code: "LK", value: "+94" },
  { label: "Bangladesh", code: "BD", value: "+880" },
  { label: "Bhutan", code: "BT", value: "+975" },
  { label: "Maldives", code: "MV", value: "+960" },
  { label: "Pakistan", code: "PK", value: "+92" },
  { label: "Afghanistan", code: "AF", value: "+93" },
  { label: "Iraq", code: "IQ", value: "+964" },
  { label: "Syria", code: "SY", value: "+963" },
  { label: "Jordan", code: "JO", value: "+962" },
  { label: "Lebanon", code: "LB", value: "+961" },
  { label: "Palestine", code: "PS", value: "+970" },
  { label: "Egypt", code: "EG", value: "+20" },
  { label: "Sudan", code: "SD", value: "+249" },
  { label: "Ethiopia", code: "ET", value: "+251" },
  { label: "Kenya", code: "KE", value: "+254" },
  { label: "Tanzania", code: "TZ", value: "+255" },
  { label: "Uganda", code: "UG", value: "+256" },
  { label: "Rwanda", code: "RW", value: "+250" },
  { label: "Burundi", code: "BI", value: "+257" },
  { label: "Mozambique", code: "MZ", value: "+258" },
  { label: "Angola", code: "AO", value: "+244" },
  { label: "Zambia", code: "ZM", value: "+260" },
  { label: "Namibia", code: "NA", value: "+264" },
  { label: "Zimbabwe", code: "ZW", value: "+263" },
];

