
export interface Campaign {
    id: stableIdtring
    name: string
    status: "Draft" | "Active" | "Paused" | "Completed"
    budget: number
    budgetLimit: number
    startDate: string
    endDate: string
    spend: number
    plays: number
    impression: number
    totalSpend: number
    startDateDuration: number // Days from now to start date
    endDateDuration: number // Days from now to end date
    screenTime: number
    setupComplete: boolean
}

export interface CampaignTableProps {
    campaigns: Campaign[]
    onSelectionChange?: (selectedIds: string[]) => void
}

import { differenceInDays, parseISO } from "date-fns"

// Calculate the total spend
const calculateTotalSpend = (spend: number, budget: number) => spend + budget;

// Adding new properties to each campaign
export const campaignTableData: Campaign[] = [
    {
        id: "tableId1",
        name: "My First Campaign",
        status: "Draft",
        budget: 789.0,
        budgetLimit: 153.0,
        startDate: "9 Jul 2025",
        endDate: "11 Jul 2025",
        spend: 0,
        plays: 0,
        impression: 0,
        screenTime: 0,
        setupComplete: false,
        startDateDuration: differenceInDays(parseISO("2025-07-09"), new Date()),
        endDateDuration: differenceInDays(parseISO("2025-07-11"), new Date()),
        totalSpend: calculateTotalSpend(0, 789.0),
    },
    {
        id: "tableId2",
        name: "My 2nd Campaign",
        status: "Draft",
        budget: 789.0,
        budgetLimit: 153.0,
        startDate: "9 Jul 2025",
        endDate: "11 Jul 2025",
        spend: 0,
        plays: 0,
        impression: 0,
        screenTime: 0,
        setupComplete: false,
        startDateDuration: differenceInDays(parseISO("2025-07-09"), new Date()),
        endDateDuration: differenceInDays(parseISO("2025-07-11"), new Date()),
        totalSpend: calculateTotalSpend(0, 789.0),
    },
    {
        id: "tableId3",
        name: "My 3rd Campaign",
        status: "Draft",
        budget: 789.0,
        budgetLimit: 153.0,
        startDate: "9 Jul 2025",
        endDate: "11 Jul 2025",
        spend: 0,
        plays: 0,
        impression: 0,
        screenTime: 0,
        setupComplete: false,
        startDateDuration: differenceInDays(parseISO("2025-07-09"), new Date()),
        endDateDuration: differenceInDays(parseISO("2025-07-11"), new Date()),
        totalSpend: calculateTotalSpend(0, 789.0),
    },
    {
        id: "tableId4",
        name: "My 4th Campaign",
        status: "Draft",
        budget: 789.0,
        budgetLimit: 153.0,
        startDate: "9 Jul 2025",
        endDate: "11 Jul 2025",
        spend: 0,
        plays: 0,
        impression: 0,
        screenTime: 0,
        setupComplete: false,
        startDateDuration: differenceInDays(parseISO("2025-07-09"), new Date()),
        endDateDuration: differenceInDays(parseISO("2025-07-11"), new Date()),
        totalSpend: calculateTotalSpend(0, 789.0),
    },
    {
        id: "tableId5",
        name: "My 5th Campaign",
        status: "Draft",
        budget: 789.0,
        budgetLimit: 153.0,
        startDate: "9 Jul 2025",
        endDate: "11 Jul 2025",
        spend: 0,
        plays: 0,
        impression: 0,
        screenTime: 0,
        setupComplete: false,
        startDateDuration: differenceInDays(parseISO("2025-07-09"), new Date()),
        endDateDuration: differenceInDays(parseISO("2025-07-11"), new Date()),
        totalSpend: calculateTotalSpend(0, 789.0),
    },
    {
        id: "tableId6",
        name: "My 6th Campaign",
        status: "Active",
        budget: 1200.0,
        budgetLimit: 200.0,
        startDate: "10 Jul 2025",
        endDate: "15 Jul 2025",
        spend: 45.5,
        plays: 1250,
        impression: 8900,
        screenTime: 125.5,
        setupComplete: true,
        startDateDuration: differenceInDays(parseISO("2025-07-10"), new Date()),
        endDateDuration: differenceInDays(parseISO("2025-07-15"), new Date()),
        totalSpend: calculateTotalSpend(45.5, 1200.0),
    },
    {
        id: "tableId7",
        name: "My 7th Campaign",
        status: "Paused",
        budget: 950.0,
        budgetLimit: 180.0,
        startDate: "8 Jul 2025",
        endDate: "12 Jul 2025",
        spend: 23.75,
        plays: 650,
        impression: 4200,
        screenTime: 67.3,
        setupComplete: true,
        startDateDuration: differenceInDays(parseISO("2025-07-08"), new Date()),
        endDateDuration: differenceInDays(parseISO("2025-07-12"), new Date()),
        totalSpend: calculateTotalSpend(23.75, 950.0),
    },
    {
        id: "tableId8",
        name: "My 8th Campaign",
        status: "Draft",
        budget: 1500.0,
        budgetLimit: 300.0,
        startDate: "9 Jul 2025",
        endDate: "15 Jul 2025",
        spend: 150,
        plays: 2000,
        impression: 7000,
        screenTime: 200,
        setupComplete: true,
        startDateDuration: differenceInDays(parseISO("2025-07-09"), new Date()),
        endDateDuration: differenceInDays(parseISO("2025-07-15"), new Date()),
        totalSpend: calculateTotalSpend(150, 1500.0),
    },
    {
        id: "tableId9",
        name: "My 9th Campaign",
        status: "Active",
        budget: 2000.0,
        budgetLimit: 400.0,
        startDate: "10 Jul 2025",
        endDate: "20 Jul 2025",
        spend: 50,
        plays: 500,
        impression: 4000,
        screenTime: 100,
        setupComplete: true,
        startDateDuration: differenceInDays(parseISO("2025-07-10"), new Date()),
        endDateDuration: differenceInDays(parseISO("2025-07-20"), new Date()),
        totalSpend: calculateTotalSpend(50, 2000.0),
    },
    {
        id: "tableId10",
        name: "My 10th Campaign",
        status: "Completed",
        budget: 1800.0,
        budgetLimit: 350.0,
        startDate: "1 Jul 2025",
        endDate: "7 Jul 2025",
        spend: 250,
        plays: 1500,
        impression: 10000,
        screenTime: 200,
        setupComplete: true,
        startDateDuration: differenceInDays(parseISO("2025-07-01"), new Date()),
        endDateDuration: differenceInDays(parseISO("2025-07-07"), new Date()),
        totalSpend: calculateTotalSpend(250, 1800.0),
    },
    {
        id: "tableId11",
        name: "Summer Campaign",
        status: "Active",
        budget: 5000.0,
        budgetLimit: 1000.0,
        startDate: "5 Aug 2025",
        endDate: "15 Aug 2025",
        spend: 100,
        plays: 3000,
        impression: 20000,
        screenTime: 400,
        setupComplete: true,
        startDateDuration: differenceInDays(parseISO("2025-08-05"), new Date()),
        endDateDuration: differenceInDays(parseISO("2025-08-15"), new Date()),
        totalSpend: calculateTotalSpend(100, 5000.0),
    },
    {
        id: "tableId12",
        name: "Christmas Campaign",
        status: "Paused",
        budget: 1500.0,
        budgetLimit: 300.0,
        startDate: "15 Dec 2025",
        endDate: "25 Dec 2025",
        spend: 200,
        plays: 4000,
        impression: 30000,
        screenTime: 500,
        setupComplete: true,
        startDateDuration: differenceInDays(parseISO("2025-12-15"), new Date()),
        endDateDuration: differenceInDays(parseISO("2025-12-25"), new Date()),
        totalSpend: calculateTotalSpend(200, 1500.0),
    },
    {
        id: "tableId13",
        name: "New Year Campaign",
        status: "Draft",
        budget: 2500.0,
        budgetLimit: 500.0,
        startDate: "1 Jan 2026",
        endDate: "15 Jan 2026",
        spend: 0,
        plays: 0,
        impression: 0,
        screenTime: 0,
        setupComplete: false,
        startDateDuration: differenceInDays(parseISO("2026-01-01"), new Date()),
        endDateDuration: differenceInDays(parseISO("2026-01-15"), new Date()),
        totalSpend: calculateTotalSpend(0, 2500.0),
    },
    {
        id: "tableId14",
        name: "Valentine's Day Campaign",
        status: "Draft",
        budget: 1000.0,
        budgetLimit: 200.0,
        startDate: "10 Feb 2026",
        endDate: "14 Feb 2026",
        spend: 0,
        plays: 0,
        impression: 0,
        screenTime: 0,
        setupComplete: false,
        startDateDuration: differenceInDays(parseISO("2026-02-10"), new Date()),
        endDateDuration: differenceInDays(parseISO("2026-02-14"), new Date()),
        totalSpend: calculateTotalSpend(0, 1000.0),
    },
    {
        id: "tableId15",
        name: "Back to School Campaign",
        status: "Draft",
        budget: 1200.0,
        budgetLimit: 250.0,
        startDate: "1 Sep 2026",
        endDate: "15 Sep 2026",
        spend: 0,
        plays: 0,
        impression: 0,
        screenTime: 0,
        setupComplete: false,
        startDateDuration: differenceInDays(parseISO("2026-09-01"), new Date()),
        endDateDuration: differenceInDays(parseISO("2026-09-15"), new Date()),
        totalSpend: calculateTotalSpend(0, 1200.0),
    },
    {
        id: "tableId16",
        name: "Holiday Sale Campaign",
        status: "Active",
        budget: 3500.0,
        budgetLimit: 700.0,
        startDate: "10 Oct 2026",
        endDate: "20 Oct 2026",
        spend: 400,
        plays: 5000,
        impression: 35000,
        screenTime: 600,
        setupComplete: true,
        startDateDuration: differenceInDays(parseISO("2026-10-10"), new Date()),
        endDateDuration: differenceInDays(parseISO("2026-10-20"), new Date()),
        totalSpend: calculateTotalSpend(400, 3500.0),
    },
    {
        id: "tableId17",
        name: "Spring Break Campaign",
        status: "Draft",
        budget: 2200.0,
        budgetLimit: 440.0,
        startDate: "1 Mar 2027",
        endDate: "31 Mar 2027",
        spend: 0,
        plays: 0,
        impression: 0,
        screenTime: 0,
        setupComplete: false,
        startDateDuration: differenceInDays(parseISO("2027-03-01"), new Date()),
        endDateDuration: differenceInDays(parseISO("2027-03-31"), new Date()),
        totalSpend: calculateTotalSpend(0, 2200.0),
    },
    {
        id: "tableId18",
        name: "Summer Fest Campaign",
        status: "Draft",
        budget: 2800.0,
        budgetLimit: 560.0,
        startDate: "15 Jun 2027",
        endDate: "30 Jun 2027",
        spend: 0,
        plays: 0,
        impression: 0,
        screenTime: 0,
        setupComplete: false,
        startDateDuration: differenceInDays(parseISO("2027-06-15"), new Date()),
        endDateDuration: differenceInDays(parseISO("2027-06-30"), new Date()),
        totalSpend: calculateTotalSpend(0, 2800.0),
    },
    {
        id: "tableId19",
        name: "Memorial Day Campaign",
        status: "Active",
        budget: 1500.0,
        budgetLimit: 300.0,
        startDate: "1 May 2027",
        endDate: "31 May 2027",
        spend: 450,
        plays: 10000,
        impression: 60000,
        screenTime: 750,
        setupComplete: true,
        startDateDuration: differenceInDays(parseISO("2027-05-01"), new Date()),
        endDateDuration: differenceInDays(parseISO("2027-05-31"), new Date()),
        totalSpend: calculateTotalSpend(450, 1500.0),
    },
    {
        id: "tableId20",
        name: "Father's Day Campaign",
        status: "Draft",
        budget: 950.0,
        budgetLimit: 190.0,
        startDate: "15 Jun 2027",
        endDate: "22 Jun 2027",
        spend: 0,
        plays: 0,
        impression: 0,
        screenTime: 0,
        setupComplete: false,
        startDateDuration: differenceInDays(parseISO("2027-06-15"), new Date()),
        endDateDuration: differenceInDays(parseISO("2027-06-22"), new Date()),
        totalSpend: calculateTotalSpend(0, 950.0),
    },
    // Additional campaigns 21 - 30
];
